<?php $user = \Auth::user();?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title> Navitas Report</title>
    <meta name="author" content="Navitas" />
    {{ Basset::show('default_layout_reports.css') }}
    <style>
        .box-shadow{background-color: #FFFFFF}
        .container{padding-top: 10px; padding-bottom: 15px;}
        .text-navitas{color: #f79546}
        table thead, footer {background-color: #f79546; color: #fff}
    </style>
</head>
<body>
    <header class="box-shadow">
        <section class="container">
            <table style="width: 100%">
                <tbody>
                <tr>
                    <td width="50%"><img src="<?= asset('assets/images/logo.png')?>" ></td>
                    <td width="50%"><div style="text-align: right" class="text-navitas"> Date: <?=date('Y-m-d H:i', strtotime('now'))?></div></td>
                </tr>
                </tbody>
            </table>
        </section>
    </header>
    <section class="container">
        <section id="content">
            @yield('content')
        </section>
    </section>

    <footer>
        <section class="container">
            <table style="width: 100%">
                <tbody>
                <tr>
                    <td width="30%">NAVITAS Digital Food Safety</td>
                    <td width="70%"><div style="text-align: right">Generated by {{$user->fullname()}}, @if($user->hasRole('hq-manager')) HQ: {{$user->headquarter()->name}} @else Unit: {{$user->unit()->name}} @endif</div></td>
                </tr>
                </tbody>
            </table>
        </section>
    </footer>
</body>
</html>